### ISSUE TITLE
version for Python 3 ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [txt2tags/txt2tags#181]
```
Hi, 

I'm in the process of porting all my code from Python 2.7 to Python 3.3.
What is currently blocking me is that txt2tags is not Python 3 compatible (also 
after 2to3 conversion).

More info: In my code I   import txt2tags   and use calls like  
txt2tags.doHeader() etc.
I get errors like:
AttributeError: 'module' object has no attribute 'ConfigMaster'


Will there be a Python 3 compatible version soon?

```

Original issue reported on code.google.com by `lhe...@gmail.com` on 12 Feb 2014 at 2:03

**Comment by B4rb3rouss** [comment]
Hi,
I was wondering how txt2tags conversion to python3 is going? Do you need help, and if so, where?

**Comment by farvardin** [comment]
I think the development is quite stalled, unfortunately.

However, there is already a functional txt2tags version for py3 which you can find there: 
https://github.com/txt2tags/txt2tags-python3

Some recent additions you can find in the current development version of txt2tags (python 2) are not included: new targets, templates etc

**Comment by B4rb3rouss** [comment]
Thanks for your answer.
I'll look into txt2tags-python3 then

**Comment by B4rb3rouss** [comment]
Thanks for your answer.
I'll look into txt2tags-python3 then.

Is there any chance that you have a list of changes made in python2 not included in python3 version ?

Regards.

**Comment by farvardin** [comment]
it's not complete yet (there were few changes since 2014 anyway), but you can have a look at the changelog, for the "Version 2.7" (not released yet):

https://github.com/txt2tags/txt2tags/blob/master/ChangeLog.t2t

15 new targets (should be quite easy to add to the py3 version), templates, a few new macros and rules, a few bugfix.

**Comment by fgallaire** [comment]
Hello @B4rb3rouss, the txt2tags-python3 is an external contribution that we don't support.

As some other great projects, and for look-alike reasons (https://www.mercurial-scm.org/wiki/SupportedPythonVersions#Python_3.x_support), txt2tags will not be ported to Python3.

**Comment by B4rb3rouss** [comment]
Too bad, once the migration to python3 done, it wouldn't take much effort to maintain, I guess.
I am wondering why one would install python2.7, even if it's not the default python version in the next debian release.

So, there is no plan to push the project a little further?

**Comment by farvardin** [comment]
everyone is free to contribute to a python 3 port of txt2tags

**Comment by fgallaire** [comment]
In fact txt2tags is byte oriented and Python 3 is unicode oriented (its only important difference with Python 2).
Some links to read:
http://lucumr.pocoo.org/2010/2/11/porting-to-python-3-a-guide/
http://lucumr.pocoo.org/2011/12/7/thoughts-on-python3/
http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/
http://lucumr.pocoo.org/2014/5/12/everything-about-unicode/

**Comment by jendrikseipp** [comment]
What makes txt2tags "byte-oriented"?

**Comment by fgallaire** [comment]
> What makes txt2tags "byte-oriented"?
The Python 2 string use.

**Comment by jendrikseipp** [comment]
RedNotebook has been feeding txt2tags with unicode strings for quite some time now, so which parts of txt2tags depend on the text being a string of bytes rather than a unicode string?

**Comment by fgallaire** [comment]
Yes you do that and you only support UTF-8 encoding. Txt2tags supports all 8-bit encoding.

**Comment by B4rb3rouss** [comment]
Still, its too bad the last changes hasn't been released since so many years, python2 or not. txt2tags is an amazing markup language and shouldn't stay like this.

By the way, what is the problem with UTF-8? Most system use it by default now.

**Comment by fgallaire** [comment]
> By the way, what is the problem with UTF-8? Most system use it by default now.

There's no problem with UTF-8, but most txt2tags users are old users and it must work fine with all there old 8-bit encoded files. This is the advice of the txt2tags's BDFL @aureliojargas, not mine.

**Comment by jendrikseipp** [comment]
Le me quote my comment from #207 for completeness:

I ported the old txt2tags 2.6 to Python 3 a while ago: https://github.com/jendrikseipp/rednotebook/blob/master/rednotebook/external/txt2tags.py

(I chose to port the released version instead of the latest revision from the repo because the released version was more stable and I didn't need any features added in later revisions.)

It contains the following disclaimer:

# This file is based on txt2tags version 2.6, but has been modified for
# RedNotebook. The changes compared to the upstream version are:
#
#   * use spaces instead of tabs
#   * port to Python 3
#   * don't escape underscores in tagged and raw LaTeX text
#   * don't use locale-dependent str.capitalize()
#   * support SVG images

Maybe it is useful for people who prefer a Python 3 version.

**Comment by fgallaire** [comment]
hello @jendrikseipp your fork should be in a repo of the txt2tags organization to be visible and easily usable by people who don't use rednotebook.

Which name should we use ? txt2tags26p3 ? or just txt2tagsp3 ? txt2tags3 looks weird to me for obvious numbering reason

**Comment by phorward** [comment]
txt2tags_v3 :relaxed:

**Comment by phorward** [comment]
> Which name should we use ? txt2tags26p3 ? or just txt2tagsp3 ? txt2tags3 looks weird to me for obvious numbering reason

Seriously: Wouldn't **text2tags** be an adequate option? It's a new name, means the same and might be a good start for an entire rework.

**Comment by jendrikseipp** [comment]
What about simply replacing the txt2tags file in the main repository with the version that works for both Python 2 and 3? Afterwards, we can cherry-pick any missing features from the replaced version.

**Comment by fgallaire** [comment]
@jendrikseipp the problem here is that you only evaluate your use of txt2tags. You can't remove years of features and say to users "I personally don't need them"

**Comment by fgallaire** [comment]
> > Which name should we use ? txt2tags26p3 ? or just txt2tagsp3 ? txt2tags3 looks weird to me for obvious numbering reason
> 
> Seriously: Wouldn't **text2tags** be an adequate option? It's a new name, means the same and might be a good start for an entire rework.

I have been the only one to fight for a name change, as txt2tags is not a good name (txt instead of text and mixed letters/number) and not famed at all

**Comment by jendrikseipp** [comment]
> the problem here is that you only evaluate your use of txt2tags. You can't remove years of features and say to users "I personally don't need them"

All new features would be available in txt2tagslite, right?

**Comment by B4rb3rouss** [comment]
Seeing some work on txt2tags is nice to read. I was worriying to have some projects I couldn't update anymore when [python2 will not be maintained](http://pythoncountdown.com/).
I hope this work will go on. Good luck !
It is a good time to change the name if necessary. text3tags ?

**Comment by farvardin** [comment]
> I have been the only one to fight for a name change, as txt2tags is not a good name (txt instead of text and mixed letters/number) and not famed at all

yeah, very good idea, you just need to move on with a new name and a new development staff! Good luck and farewell!

**Comment by jendrikseipp** [comment]
I created a dedicated repository for txt2tags version 2.6 ported to Python 3 at https://github.com/jendrikseipp/txt2tags.

**Comment by phorward** [comment]
Do you plan to continue further development and project maintenance?

**Comment by jendrikseipp** [comment]
Yes, I do. Any help is appreciated :-)

**Comment by jendrikseipp** [comment]
We moved the version for Python 3 to https://github.com/txt2tags/txt2tags/tree/v3.

**Comment by lbartoletti** [comment]
Thanks @jendrikseipp
