### ISSUE TITLE
Error when converting to txt

### ISSUE THREAD

**Issue by flamenco108** [txt2tags/txt2tags#187]
Trying to prepare txt2tags to use I trained to-text conversion. I used UTF-8 text file. This file I trained with conversion to html and it works, but not with plain text, where I got such an error:

    flamenco@maluch:~/Docs/TXT/Mongolowie/txt2tags$ txt2tags -t txt mongol.t2t
    Sorry! Txt2tags aborted by an unknown error.
    Please send the following Error Traceback to the author (verde@aurelio.net):

    Traceback (most recent call last):
      File "/home/flamenco/bin/txt2tags", line 10236, in <module>
        exec_command_line()
      File "/home/flamenco/bin/txt2tags", line 10230, in exec_command_line
        convert_this_files(infiles_config)
      File "/home/flamenco/bin/txt2tags", line 8771, in convert_this_files
        outlist = doHeader(source_head, myconf)
      File "/home/flamenco/bin/txt2tags", line 8114, in doHeader
        head_data['BODY'] = '\n'.join(config['fullBody'])
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 4: ordinal not in range(128)

**Comment by fgallaire** [comment]
You need to add your encoding at the beginning of the file:
%!encoding: utf-8

And you should try the -t aat or -t aap targets if you want advanced text rendering.

**Comment by flamenco108** [comment]
Sorry for the late answer, but I thought, that your advice is enough. I don't know, perhaps it is, but if yes, then there some minor corrections in helps, manuals and program messages are perhaps needed. I mean, the explanation, that `txt target` is not just the `Plain Text`, but `Plain Text in ASCII encoding`. But maybe it does not.

Below is the config made by --dump-config. As you can see, the `utf-8` is declared. I tried also `UTF-8`.

In fact I use the `UTF-8` in text files, as I write in Polish, where are some typical Polish characters.

I tried follow your advice and used also the `aat` and `aap` targets. There are the problem basically with dashes (—):
```
flamenco@maluch:~/www/txt2tags$ txt2tags -t aat mongol.t2t
txt2tags: Error: Invalid PreProc filter replacement: ' — '
```
I thought, that the problem is in usage of dashes by %!preproc (as you can see, I learn to play with the config), but it isn't. Above message is shown in aat and aap targets, but with txt target I get:
```
flamenco@maluch:~/www/txt2tags$ txt2tags -t txt  mongol.t2t
Sorry! Txt2tags aborted by an unknown error.
Please send the following Error Traceback to the author (verde@aurelio.net):

Traceback (most recent call last):
  File "/home/flamenco/bin/txt2tags", line 10236, in <module>
    exec_command_line()
  File "/home/flamenco/bin/txt2tags", line 10230, in exec_command_line
    convert_this_files(infiles_config)
  File "/home/flamenco/bin/txt2tags", line 8771, in convert_this_files
    outlist = doHeader(source_head, myconf)
  File "/home/flamenco/bin/txt2tags", line 8114, in doHeader
    head_data['BODY'] = '\n'.join(config['fullBody'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 7: ordinal not in range(128)
```

The problem seems to be in `--target txt` option - it looks like **this option (txt) works only on ASCII**. Is it true, undocumented feature or bug?

I use the **2.6 version** of txt2tags, downloaded at **2015-05-13**.

```txt2tags
RAW config for source document
  (all)    target........: html
  (all)    encoding......: utf-8
  (html)   options.......: --dirname http://krzysztof.smirnow.eu/t2t --css-sugar
  (html)   stylepath.....: http://krzysztof.smirnow.eu/t2t/style.css
  (html)   style.........: http://krzysztof.smirnow.eu/t2t/style.css
  (xhtml)  options.......: --dirname http://krzysztof.smirnow.eu/t2t --css-sugar
  (xhtml)  stylepath.....: http://krzysztof.smirnow.eu/t2t/style.css
  (xhtml)  style.........: http://krzysztof.smirnow.eu/t2t/style.css
  (html)   options.......: --dirname http://krzysztof.smirnow.eu/t2t --mask-email
  (moin)   options.......: --dirname http://krzysztof.smirnow.eu/t2t --mask-email
  (txt)    options.......: --dirname http://krzysztof.smirnow.eu/t2t --enum-title
  (tex)    options.......: --dirname http://krzysztof.smirnow.eu/t2t --toc
  (all)    options.......: --dirname http://krzysztof.smirnow.eu/t2t --toc-level 4
  (tex)    stylepath.....: http://krzysztof.smirnow.eu/t2t/polski
  (tex)    style.........: polski
  (tex)    postproc......: ('LaTeX', '\\\\LaTeX{}')
  (tex)    postproc......: ('\\bTeX', '\\\\TeX{}')
  (xhtml)  preproc.......: ('\\\\\\\\', 'LbrL')
  (html)   preproc.......: ('\\\\\\\\', 'LbrL')
  (tex)    preproc.......: ('\\\\\\\\', 'LbrL')
  (txt)    preproc.......: ('\\\\\\\\', '\\n')
  (xhtml)  postproc......: ('LbrL', '<br />')
  (html)   postproc......: ('LbrL', '<BR>')
  (tex)    postproc......: ('LbrL', '\\\\\\\\')
  (html)   preproc.......: ('/\\*(.*?)\\*/', '<!-- \\1 -->')
  (xhtml)  preproc.......: ('/\\*(.*?)\\*/', '<!-- \\1 -->')
  (xhtml)  preproc.......: ('/\\*(.*?)\\*/', '\\% \\1')
  (html)   preproc.......: ('<!--(.*?)-->', '<!KARMAPACZIENNO\\1KARMAPACZIENNO>')
  (html)   postproc......: ('<!KARMAPACZIENNO(.*?)KARMAPACZIENNO>', '<!-- \\1 -->')
  (xhtml)  preproc.......: ('<!--(.*?)-->', '<!KARMAPACZIENNO\\1KARMAPACZIENNO>')
  (xhtml)  postproc......: ('<!KARMAPACZIENNO(.*?)KARMAPACZIENNO>', '<!-- \\1 -->')
  (html)   postproc......: ('\\(c\\)', '&copy;')
  (xhtml)  postproc......: ('\\(c\\)', '&copy;')
  (tex)    preproc.......: ('\\(c\\)', '\\copyright')
  (txt)    postproc......: ('\\(c\\)', '\xc2\xa9')
  (html)   postproc......: ('\\(tm\\)', '&trade;')
  (xhtml)  postproc......: ('\\(tm\\)', '&trade;')
  (tex)    preproc.......: ('\\(tm\\)', '\\texttrademark')
  (txt)    postproc......: ('\\(tm\\)', '\xe2\x84\xa2')
  (html)   postproc......: ('\\(r\\)', '&reg;')
  (xhtml)  postproc......: ('\\(r\\)', '&reg;')
  (tex)    preproc.......: ('\\(r\\)', '\\textregistered')
  (txt)    postproc......: ('\\(r\\)', '\xc2\xae')
  (html)   postproc......: ('(\\s+[aiouwz])\\s+', '\\1&nbsp;')
  (xhtml)  postproc......: ('(^|\\s+[aiouwz])\\s+', '\\1&nbsp;')
  (tex)    postproc......: ("(^|\\s+[aiouwz])\\s+'", '\\1~')
  (html)   postproc......: ('\\^\\^(.*?)\\^\\^', '<sup>\\1</sup>')
  (html)   postproc......: ('__(.*?)__', '<sub>\\1</sub>')
  (all)    postproc......: (',,', '\xe2\x80\x9e')
  (all)    postproc......: ("\\'\\'", '\xe2\x80\x9d')
  (all)    postproc......: ('\\s+([\\,\\.;:!?])', '\\1')
  (txt)    preproc.......: ('\\s-\\s', ' --- ')
  (txt)    preproc.......: ('^-\\s', '--- ')
  (all)    preproc.......: ('\\s-\\s', ' \xe2\x80\x94 ')
  (all)    preproc.......: ('^-\\s', '\xe2\x80\x94 ')
  (html)   postproc......: ('\\.\\.\\.', '&hellip;')
  (xhtml)  postproc......: ('\\.\\.\\.', '&hellip;')
  (txt)    postproc......: ('\\.\\.\\.', '\xe2\x80\xa6')
  (tex)    postproc......: ('\\.\\.\\.', '\\\\dots')

RAW config for command line
  (all)    target........: txt
  (all)    dump-config...: ON
  (all)    infile........: mongol.t2t
  (all)    realcmdline...: ['-t', 'txt', '--dump-config', 'mongol.t2t']

Full PARSED config
        currentsourcefile: mongol.t2t
           dump-config...: ON
           encoding......: utf-8
           enum-title....: ON
           infile........: mongol.t2t
           realcmdline...: -t, txt, --dump-config, mongol.t2t
           sourcefile....: mongol.t2t
           target........: txt
           toc-level.....: 4

Active filters
           preproc.......: \\\\  ->  \n
           preproc.......: \s-\s  ->   ---
           preproc.......: ^-\s  ->  ---
           preproc.......: \s-\s  ->   —
           preproc.......: ^-\s  ->  —
           postproc......: \(c\)  ->  ©
           postproc......: \(tm\)  ->  ™
           postproc......: \(r\)  ->  ®
           postproc......: ,,  ->  „
           postproc......: \'\'  ->  ”
           postproc......: \s+([\,\.;:!?])  ->  \1
           postproc......: \.\.\.  ->  …
```

Thanks for help anyway.

**Comment by flamenco108** [comment]
**I don't know, what to do, perhaps this issue should be deleted**, or the problem is in some more advanced config procedures. I made the simplest test and txt2tags passed it perfectly:
```
flamenco@maluch:~/www/txt2tags$ cat aaa.t2t
Myself
Test of Polish/Unicode characters in txt2tags
2015-05-20
%!encoding: utf-8

Some Polish characters:

zażółć gęślą jaźń

ZAŻÓŁĆ GĘŚLĄ JAŹŃ

dash —
endash –

That's all
```
Convert to aat
```
flamenco@maluch:~/www/txt2tags$ txt2tags -t aat aaa.t2t
txt2tags wrote aaa.aat
flamenco@maluch:~/www/txt2tags$ cat aaa.aat

========================================================================


                               +--------+
                               | Myself |
                               +--------+


           +-----------------------------------------------+
           | Test of Polish/Unicode characters in txt2tags |
           +-----------------------------------------------+


                             +------------+
                             | 2015-05-20 |
                             +------------+


========================================================================

Some Polish characters:

zażółć gęślą jaźń

ZAŻÓŁĆ GĘŚLĄ JAŹŃ

dash —
endash –

That's all
```
Convert to txt
```
flamenco@maluch:~/www/txt2tags$ txt2tags -t txt aaa.t2t
txt2tags wrote aaa.txt
flamenco@maluch:~/www/txt2tags$ cat aaa.txt
Myself
Test of Polish/Unicode characters in txt2tags
2015-05-20


Some Polish characters:

zażółć gęślą jaźń

ZAŻÓŁĆ GĘŚLĄ JAŹŃ

dash —
endash –

That's all

```

**Comment by farvardin** [comment]
it's high time we release a 2.7 version of txt2tags and also utf-8 should
be default (maybe it's already in the 2.7 dev version, I don't remember)

2015-05-20 9:26 GMT+02:00 flamenco108 <notifications@github.com>:

**Comment by fgallaire** [comment]
@favardin
As txt2tags uses Python 2, it's string based and utf-8 can't be the "default".

@flamenco108
For support utf-8 I've done a lot of hacks on the txt2tags master, as the content is first imported as a string, then the encoding option 'utf-8' is tested by reimporting the content.

Could you test the master txt2tags ?

**Comment by farvardin** [comment]
I meant default utf-8 for exporting everything, and option for using other
encoding. I'm glad you've confirmed that it was fixed in the current devel
version

2015-05-20 13:24 GMT+02:00 Florent Gallaire <notifications@github.com>:

**Comment by fgallaire** [comment]
@farvardin not really in fact. The base concept of the encoding option in txt2tags is that it's purely declarative and don't check or test anything. It's useful for targets like TeX or HTML where you need to declare the encoding, but you can lie and txt2tags can't know it and so can't help you.

Txt2tags only process strings of 1 byte (8 bits) chars. It's OK for all classical encoding, but not for UTF-8 as you can have a chars coded in more than 1 byte. But in fact, know the real length of a char is only needed to do text formatting. So my hacks apply only to this targets:
- txt
- rst
- all the "ASCII art"
- mgp (as I added a support of ascii rendering for tables)
