### ISSUE TITLE
Use Git submodules

### ISSUE THREAD

**Issue by fgallaire** [txt2tags/txt2tags#189]

**Comment by jendrikseipp** [comment]
What do you want to use them for?

**Comment by fgallaire** [comment]
For a maximum of directories : doc, extras, test, website at least.

**Comment by jendrikseipp** [comment]
For each directory we should consider carefully whether moving it into a submodule is helpful. E.g. I'd say that indeed the website could be moved outside the main repo, but the tests should definitely stay. What are the benefits of moving doc and extras out of the main repo (apart from a cleaner history maybe)?

**Comment by fgallaire** [comment]
- yes cleaner history
- lightweight checkout
- shared repos (doc and test could be shared between txt2tags and txt2tagslite repos)

**Comment by fgallaire** [comment]
old/ and website/ are now submodules.

**Comment by fgallaire** [comment]
doc/ is now submodule.

**Comment by fgallaire** [comment]
The two "non dev" directories (website/ and doc/) and the archive one (old/) are now submodules. Pleasantly, they were the biggest directories, so the txt2tags checkout for dev purpose is now 3 times lighter.
This repos, particularly the doc/ one, are now more visible to non dev contibutors.
I agree with @jendrikseipp that all the dev related stuff (test/, lib/,...) should stay here for the moment.

About the extra/ repo, IMO it should be totally removed of the txt2tags repo, not kept as a submodule, and each project from it should have its own repo.

**Comment by jendrikseipp** [comment]
I totally agree.

**Comment by farvardin** [comment]
I think it's easier to checkout or commit only one repo rather than working
into 20 different repos...
Obviously some "bigger" projects could leave the extra folder (and txt2tags
repo as well), but some other should be kept there.

2015-07-03 12:08 GMT+02:00 Jendrik Seipp <notifications@github.com>:

**Comment by fgallaire** [comment]
@farvardin I agree with you, IMO you are the leader/maintainer of the extras stuff, so organise it as you prefer, but remove the extras/ repo as soon as possible.

My only wish is that each other language implementations of txt2tags/markon has its own repo. The name of the repo should be with the suffix .nameofthelanguage and not as the "-php" which should be fixed.

**Comment by fgallaire** [comment]
If anyone know how to rewrite the history to remove to move the website/ and doc/ commits to the submodules, this could be great !

**Comment by aureliojargas** [comment]
The following repositories were created from the `extras` folders, preserving the full commit history.

* https://github.com/txt2tags/plugins
* https://github.com/txt2tags/tools

**Comment by fgallaire** [comment]
@aureliojargas without official announce, a new commit has been done on the SVN repo after this export.
Could you fix that and remove the extras folder ? and fix the history for the submodules ? After that we could be able to work effectively on txt2tags !

**Comment by fgallaire** [comment]
@aureliojargas @farvardin and txt2tags-php more up to date in the svn repo too. Is it possible to fix that too ? and with the name txt2tags.php ?

**Comment by fgallaire** [comment]
@aureliojargas could you move the website/, doc/ and old/ history from the txt2tags repo to the good submodule, after that we could begin to commit the fix needed to release txt2tags 2.7 as soon as possible.

**Comment by fgallaire** [comment]
@aureliojargas could you move the (unsupported) python3 branch to its own repo ?

**Comment by aureliojargas** [comment]
@fgallaire you can do those changes easily:

* Move python3 branch to another repo:
http://stackoverflow.com/questions/2227062/how-do-i-move-a-git-branch-out-into-its-own-repository

* Move a folder to a new repo:
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

* Copy commits from the main repo to another repo:
http://stackoverflow.com/questions/5120038/is-it-possible-to-cherry-pick-a-commit-from-another-git-repository

* You can still access the old SVN repo, if necessary:
`git svn clone https://txt2tags.googlecode.com/svn/trunk`

**Comment by fgallaire** [comment]
@aureliojargas OK, I will try. But I need access to the old googlecode website back.

**Comment by fgallaire** [comment]
doc/, website/ and old/ submodules now have their histories and the former python3 branch is now in the txt2tags-python3 repo.

**Comment by fgallaire** [comment]
@farvardin it's time to update the extras repos and remove the extras directory in the txt2tags repo to complete the migration.

**Comment by farvardin** [comment]
I'm sorry I don't know how to use git submodules, and in additing I don't really see the point of separating the projects like that, it means someone who want to get all the development code for all txt2tags tools will need to pull off the txt2tags directories 4 or 5 times, I find this rather un-KISS. The simpler the better.

In addition, the "extra" directory is less than 1 Mb, so it's not really a big deal. I think only the "retxt2tags" tool is rather anecdotic and could be removed, but the rest provides several useful tools for 3rd party software. But feel free to organise that like you wish, you can delete whatever you want, I have a copy of the whole project on my hard-drive...

**Comment by fgallaire** [comment]
The only problem is to have the last version of all the projects.
A good organization of the codebase is a need if we want to attract some new devs.

**Comment by fgallaire** [comment]
extras/ is finally removed, replaced by the plugins/ and tools/ submodules.
@farvardin you have two commits to port to make this stuff up-to-date:
Aug 2014 [extra] updating plugin for dokuwiki
Feb 2016 updated pmwiki cookbook for php 5.5+

**Comment by fgallaire** [comment]
@farvardin the txt2tags-php is not up-to-date, **7 commits** done in the txt2tags repo have to be ported to the txt2tags-php one. And in the actual txt2tags-php you don't have preserved the full commit history. So IMO you should delete the actual repo and do the same work for txt2tags-php than Aurelio for plugins/ and tools/ and me for doc/, old/ and website/.

**Comment by fgallaire** [comment]
@farvardin I have done all the work for txt2tags-php which is now the txt2tags.php submodule of the txt2tags repo, up-to-date and with a full commit history.

**Comment by fgallaire** [comment]
@farvardin the code of the txt2tags js implementations is in one of your personal repo, do you agree to move it in a txt2tags organization repo ? it would be more visible and easy to find for users and contributors.

**Comment by aureliojargas** [comment]
Since all the moving was already done, and the only request left to @farvardin is unanswered for some years, we can consider that a "no".

Closing this ticket.
