### ISSUE TITLE
Txt2tags new name

### ISSUE THREAD

**Issue by fgallaire** [txt2tags/txt2tags#192]
"txt2tags v3:
New Name?
Maybe it's a good opportunity to improve the program name?
txt2tags is hard to pronounce and it is common to see it referred as t*e*xt2tags.
A new, simple name, could help the project to spread. Markdown is a killer name, maybe we could find something as strong and simple?"

Lot of discussions about that on the old site.

My proposition is "Markon":
- MarkON is NOT the name of a software, but the name of a MARKUP SYNTAX
- txt2tagslite released as markon.py, and the reference implementation of the MarkON syntax
- all other implementations named in the same way (markon.php, markon.js and so on)

I bought http://markon.io domain name ([why an .io domain](http://www.russellbeattie.com/blog/artisanal-websites-the-rise-of-io-domains-for-well-crafted-web-services)).

I did a logo:
![MarkON logo](http://dl.flext.net/markon.png)

**Comment by jendrikseipp** [comment]
I believe having a bad name is better than having a changing name. Also, I think that txt2tags is not a bad name at all. It follows the traditional something2something converter naming and describes what it does very concisely. It's not hard to pronounce in my opinion and it doesn't matter if someone refers to it as text2tags.

**Comment by farvardin** [comment]
I think roughly the same...

I also think that txt2tags is a good name. Markdown is not **that** 
great, the "down" part doesn't sound very positive in my opinion...

Why not going to "CommonMark" then? ;) (or "CommonMark extended")

About changing the name, it is double edged, it could bring more people 
who could have some old prejudice against txt2tags, or who are only 
interested in "new things", but on the other hand it could confuse 
people who already like txt2tags. Really I don't know what is better for 
the project in the future, but I think keeping the current name (and 
legacy) would be safer.

**Comment by farvardin** [comment]
ultimately, I think it would be best if Aurelio could choose himself 
which is the best option, to keep the current name, which is around for 
almost 14 years, and to give it a new start...

**Comment by aureliojargas** [comment]
In my opinion, after 14 years using txt2tags, renaming now won't do any good. 

I find interesting the @fgallaire ideia to focus on the markup and have different implementations. But I guess that is better handled as a fork or a new project, not a rename of the current project. In the future, the current txt2tags could say it supports the Markon syntax for input files.

**Comment by fgallaire** [comment]
@jendrikseipp changing name is not that a big deal (Mandrake->Mandriva, Phoenix->Firebird->Firefox, etc.)
@farvardin if you want a new start for txt2tags, the best way is to change the name:
- Do you want to use txt2tags ?
- Ouch, If I have lived without it during 14 years, I can continue !
- Do you want to use Markon ?
- Oh, the brand new markup language that rocks them all ? Yes !!
People who already love txt2tags are advanced users and will not be lost at all !
@aureliojargas a fork or a new project ? If you "quit txt2tags" as you indicated in a personal mail of 4/19/2014 (no more fun or motivation), it should not be fork or new project (do you imagine Linus leaving Linux and saying Linux 2.6 is the last Linux, please fork or do a new project). I know it's your baby, but that's not good management, or you continue to support it, or you let it free to evolve.

**Comment by aureliojargas** [comment]
@fgallaire that was just my personal opinion, not a decision. I'm not the dictator anymore :)

**Comment by fgallaire** [comment]
@aureliojargas txt2tags will always need you.

**Comment by fgallaire** [comment]
I propose to use the name MarkON for the syntax.
txt2tags stay txt2tags.
markon.language for all the other implementations.
".mon" (instead of ".t2t") for the file extension.

If it's ok we should:
1) rename txt2tags-php in markon.php, and release markon.js (@farvardin i's ok ?)
2) change the name of the Pandoc writer and add the new file extension (I can do that)
3) add the .mon extension in txt2tags (I can do that)

I need quick feedbacks, because I want to move forward.

**Comment by jendrikseipp** [comment]
Can you please tell me the advantages of decoupling the syntax from the markup converter?

**Comment by fgallaire** [comment]
@jendrikseipp it's more clear to explain, differentiate "txt2tags the software" from "txt2tags the syntax" is a mess ! And a try to be more successful with a good naming/branding for the syntax :-)

**Comment by jendrikseipp** [comment]
If we change the name of the syntax, the differentiation "txt2tags the
software" vs. "txt2tags the syntax" would become "txt2tags the
software that accepts the markon syntax" vs. "markon the syntax that
can be used by txt2tags".

I think splitting the markup language from the software is a bad idea.
There are already countless markup languages around and I believe that
nobody cares for another language. The txt2tags syntax is nice and
simple, but it doesn't have any major advantages over other languages.
Choosing a syntax is mostly a matter of taste. The main advantages of
txt2tags are the pre-/postproc filters, but I doubt any markup software
will implement these (e.g. pandoc doesn't). What sets txt2tags apart is
the **combination** of an *easy syntax* and *numerous export formats*.
I think nobody is going to pick txt2tags for just one of these parts.
If I want an easy syntax I can choose from many markup languages, some
of which are much more widely used. If I want numerous export formats,
I can just use pandoc.

Another concern is that renaming the syntax will destroy most of the
publicity that txt2tags has. Today, people visiting the pandoc website
or https://en.wikipedia.org/wiki/Lightweight_markup_language will see
information about txt2tags and might look at the txt2tags website to
find out more about it. If these pages mentioned only "markon", nobody
would find out about txt2tags.

If we want to strengthen the brand, we should not throw our existing
brand overboard, but try to improve txt2tags. We should clean it up,
fix bugs and make releases more frequently. To me, this sounds much
more helpful than confusing users with a "new" markup language.

**Comment by aureliojargas** [comment]
@jendrikseipp :+1:

**Comment by fgallaire** [comment]
txt2tags fail as brand since 15 years.
Pandoc is very successful and pandoc!=markdown, nobody is confused !
MarkON will be lightweight markup to html converters in any language, txt2tags a powerful tool for the MarkON syntax, and the reference implementation.

**Comment by farvardin** [comment]
Nobody prevents you to create a new project called MarkON for working on a new syntax (or reuse the txt2tags one). But like the other I don't see the point of renaming parts of the current project, keeping txt2tags the python implementation as a tool, while renaming txt2tags-php the php implementation, and breaking all the current projects expecting a file called txt2tags.class.php for instance. 

For me the best about txt2tags is all the things together, the whole project: the syntax, the implementations, the pre/postprocessors. For me it will always be txt2tags. It didn't fail as a brand since 15 years: only markdown gained some notoriety (even if I think as a markup bbcode is more widespread), the other markups like txt2tags, Textile, reStructuredText, kept a very small part of the market share. And the average guy doesn't know anything about lightweight markup language, be it txt2tags, markdown or markon.

**Comment by fgallaire** [comment]
Be happy to fail and wanted to continue is something I can't understand. If txt2tags was a powerful tool and the reference implementation of the successfull syntax MarkON, it will have so more success, as Pandoc ! We know the way to have success, this is the Markdown/Pandoc way, and you don't want to go on it :-(

Be afraid to break one link about txt2tags on wikipedia is a joke, and "all the current projects expecting a file called txt2tags.class.php" an other one (which projects except yours ??) ! 

But the world is conservative by nature, people are happy of what they have and afraid to change. Perfect !!

**Comment by fgallaire** [comment]
After stormy discussion, decision has been made NOT to change the name of txt2tags (the software and the syntax).
