### ISSUE TITLE
Bad key parsing in source's Config section

### ISSUE THREAD

**Issue by bAndie91** [txt2tags/txt2tags#194]
I noticed that config keys with dash in their name do not get parsed in the source document.
eg. `%!mask-email:on`
I think it can be fixed by putting a "-" in regexp char class in parse_line() method.
I have 2.6-3 by Debian and discussed line is 2921 in this version.

**Comment by aureliojargas** [comment]
Hi @bAndie91,

Thanks for your suggestion.

Instead of creating a specific setting for every command line option, long ago we decided to add the generic `%!options` setting, where you can specify any command line option and its possible parameters. Example:

    %!options: --toc --toc-level 2 --enum-title

or, in the case you've mentioned:

    %!options: --mask-email
