### ISSUE TITLE
Keep language stable

### ISSUE THREAD

**Issue by jendrikseipp** [txt2tags/txt2tags#196]
I noticed some recent changes to the language. In particular, the $$formula$$, ^^supertext^^ and ,,subtext,, markers were introduced. This is problematic for two reasons. First, I think changes to the language need to be discussed with all developers. Second, we are in the process of stabilizing and cleaning up the implementation for the 2.7 release. We should not extend txt2tags with new features until the release.

**Comment by aureliojargas** [comment]
Now on GitHub, Pull Requests could be used to discuss new features before merging them into master.

**Comment by fgallaire** [comment]
@jendrikseipp no **changes**, but needed **additions**.

**Comment by farvardin** [comment]
I don't think it's needed at all, we can easily add those specific syntax with preproc and postproc. If you want to rename txt2tags and add syntax in the core without noticing other people in the staff, maybe you could start a fork or derivative instead? It's what I did with textallion because I had ideas which would interfere with the txt2tags syntax

**Comment by fgallaire** [comment]
Hello preproc and postproc are great for specific stuff, not for basic features that must be built-in.

**Comment by jendrikseipp** [comment]
Another addition that makes txt2tags harder to maintain is the ascii-art targets. I think adding them to the txt2tags core is a step in the wrong direction. They would be useful and maintainable as extensions, but the way they are implemented at the moment makes the code much more complex, they add many commandline arguments and it is unclear whether a significant number of users will find them useful. Given that they are non-standard formats and there is the txt target, their utility is questionable. If we release version 2.7 with the ascii-art targets we can't just remove them later, but have to maintain them, so I'm strongly in favour of removing them. Once txt2tags has an extension system we can think about how to add them in a way that keeps txt2tags simple.

**Comment by fgallaire** [comment]
Art targets are part of txt2tags since txt2tags released in 2010.

**Comment by jendrikseipp** [comment]
Yes, I guess the ship has sailed for the original "art" target. However, comparing the help output from version 2.6 and the current development version, there are 6 additional ascii-art targets (aap, aapp, aapw, aas, aasw, aatw).

**Comment by aureliojargas** [comment]
I agree with @jendrikseipp about the art targets. They are like another program inside txt2tags.

**Comment by fgallaire** [comment]
@jendrikseipp and @aureliojargas txt2tags has evolved, if you want to use txt2tags 2.5 it's possible, maybe you could fork it.

**Comment by jendrikseipp** [comment]
I believe this issue has been resolved by the v2/v3 split.
