### ISSUE TITLE
Unable to embed links in headings.

### ISSUE THREAD

**Issue by manjo-git** [txt2tags/txt2tags#203]
txt2tags does not treat html links in headings correctly. For example if I have:

            == [This is a link http://blah.com/link/to/something.html] == 

- It generates the heading as html code:
```
 <H2>[This is a link http://blah.com/link/to/something.html]</H2] 
```
Instead of generating 
```
<h4><a href="http://blah.com/link/to/something.html">This is a link</a></h4>
```
- It generates the TOC entry as html code: 
```
<LI><A HREF="#toc7">[This is a link http://blah.com/link/to/something.html]</A> 
```
Instead of just having 
```
"This is a link"
```

**Comment by farvardin** [comment]
In the txt2tags markup syntax, you're not supposed to use links inside heading marks (like you're not supposed to use italics, bold etc in the headings).

http://txt2tags.org/rules.html

If you really need to create a link into your headings, use some postprocessor tricks.
