### ISSUE TITLE
sub-line behin italic

### ISSUE THREAD

**Issue by OrkaEdison** [txt2tags/txt2tags#205]
i use //word// for italic and i have __sub-line__ 
[txt-sample.zip](https://github.com/txt2tags/txt2tags/files/402099/txt-sample.zip)
as italic

**Comment by farvardin** [comment]
I'm sorry but I don't understand your problem. Could you please post a whole example?
If you use //for italic//, and you have a line behind the first one, this new line won't be in italic, unless you've make an error in the syntax.

**Comment by OrkaEdison** [comment]
this is an example, underline work on xhtml export but not in man export... italic too...

[txt2tags-bugs_rep.tar.gz](https://github.com/txt2tags/txt2tags/files/403669/txt2tags-bugs_rep.tar.gz)

**Comment by farvardin** [comment]
I think GROFF (the markup used for man pages) doesn't support underline (what in txt2tags is marked __like this__). It will be ignored in man export. Italic and bold are supported in groff. See http://linuxfocus.org/common/src/article309/groff_man_7.html

Yet, in my terminal (and probably in most other people as well), italic text won't be displayed as italic font face but as underline (it's probably consided as "emphasis"). It's certainly configurable somewhere in the terminal settings.

http://linux.die.net/man/7/groff_mdoc

So we can't do anything from the txt2tags part I'm afraid. Désolé.

**Comment by OrkaEdison** [comment]
ok... it's just for do my use database, may be it's a good idea to add it in groff man page...
