### ISSUE TITLE
Dead links on the download page

### ISSUE THREAD

**Issue by cypriani** [txt2tags/txt2tags#208]
Hi again,

Several links are dead on http://txt2tags.org/download.html
Notably, the three main download links: all platforms, Windows (and "download just the Python script below", MacOS.
And also the link to the Python 3 branch.

And in the right column: the identi.ca link.

Matteo

**Comment by farvardin** [comment]
Salut Matteo,

merci pour l'info.

I don't have the txt2tags-2.6.tgz file on this computer, but I should have kept it somewhere. I don't have the mac os x version at all. Meanwhile, I've tried to change the website through this file, I think it should update the website once in a day: https://github.com/txt2tags/website/blob/master/download.html
We'll see. If it works, I'll put a proper link for the txt2tags-2.6.tgz file (and I'll probably use a zip instead)

**Comment by cypriani** [comment]
Le vendredi 28 octobre 2016, 00:11:23 EDT farvardin a écrit :
> I don't have the txt2tags-2.6.tgz file on this computer, but I should have
> kept it somewhere.

You can retrieve it from the Debian archive:

http://http.debian.net/debian/pool/main/t/txt2tags/txt2tags_2.6.orig.tar.gz

(Just rename it to txt2tags-2.6.tgz, it's the exact same file.)


> […] (and I'll probably use a zip instead)

I don't think this is a good idea, as Debian (and possibly
other distros) does not support zip upstream archives. So please keep a
.tar.{xz,bz2,gz} if possible, that will save the maintainers the job to repack 
to a tarball for every new release (not that they are terribly frequent ;-).

Besides, MacOS has tar, and free software tools (like p7zip) are available on 
Windows to unpack tarballs.

À plus,
  Matteo

**Comment by cypriani** [comment]
Just noticed that the OpenBSD link is dead as well. Possible replacement 
links:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/textproc/txt2tags/
http://ports.su/textproc/txt2tags
http://openports.se/textproc/txt2tags

**Comment by cypriani** [comment]
The automatic update thing doesn't seem to be working…

**Comment by farvardin** [comment]
No :(
I've sent an email to the owner (Aurelio).

**Comment by aureliojargas** [comment]
Thanks for the report!

I have fixed all the old Google Code broken links, the OpenBSD link and removed the identi.ca menu entry (see mentioned commits on this thread).

I have also fixed the automatic update. It's back updating the website everyday at noon (UTC).
