### ISSUE TITLE
List available targets in the README

### ISSUE THREAD

**Issue by andreasabel** [txt2tags/txt2tags#226]
The README shows a big nice table to compare the features of the different versions of txt2tags.  
This table gives the impression that v3 hardly supports any targets, only HTML and MarkDown.
A careful look reveils the small print _Unlisted features are available in all versions._
However, a picture says more than a 1000 words.

To give the correct impression, I suggest to add all supported targets to the table, even if the lines then just contain 3 checkmarks.

This is the v3 list of targets:
```
$ txt2tags --targets
adoc    AsciiDoc document
creole  Creole 1.0 document
dbk     DocBook document
doku    DokuWiki page
gwiki   Google Wiki page
html    HTML page
lout    Lout document
man     UNIX Manual page
md      Markdown document
mgp     MagicPoint presentation
moin    MoinMoin page
pmw     PmWiki page
sgml    SGML document
tex     LaTeX document
txt     Plain Text
wiki    Wikipedia page
```

**Comment by jendrikseipp** [comment]
Good point. Would you care to fix this in a pull request?

**Comment by andreasabel** [comment]
Er, the README is your advertisement page for `txt2tags`.  I am giving information what impression an outsider is getting on this project.

I already found my information, so I have no further interest in this issue.  But the maintainers invested in the project maybe should have.

(Sorry for not being as nice as I could be if I had more time today.)

**Comment by andreasabel** [comment]
Ok, I am really bad at saying no, here you go: https://github.com/txt2tags/txt2tags/pull/229

**Comment by aureliojargas** [comment]
@andreasabel Thank you very much for the report and for your kind contribution ❤️
