### ISSUE TITLE
Is txt2tags still in development?

### ISSUE THREAD

**Issue by dpy013** [txt2tags/txt2tags#237]
hi
@aureliojargas 
Currently txt2tags has 120 problems waiting to be solved, and 93 problems have been solved.
I've been using txt2tags please will the next txt2tags be updated?
thanks

**Comment by aureliojargas** [comment]
Hi @dingpengyu, 

The latest development for txt2tags is happening in the [v3 branch](https://github.com/txt2tags/txt2tags/commits/v3) (maintained by @jendrikseipp) and is releasing new versions here: https://github.com/txt2tags/txt2tags/releases.

About those 120 opened issues, not all of them are problems, we also use the issue system for ideas, suggestions, refactors,  and general improvements. For example, [49 of those are marked as enhancements](https://github.com/txt2tags/txt2tags/issues?q=is%3Aissue+is%3Aopen+label%3AType-Enhancement).

By the way, that list of open issues have some very old tickets (migrated from the old Google Code system) that may not even be relevant anymore. Surely we could do a clean up there.

**Comment by dingpengyu** [comment]
> Hi @dingpengyu,
> 
> The latest development for txt2tags is happening in the [v3 branch](https://github.com/txt2tags/txt2tags/commits/v3) (maintained by @jendrikseipp) and is releasing new versions here: https://github.com/txt2tags/txt2tags/releases.
> 
> About those 120 opened issues, not all of them are problems, we also use the issue system for ideas, suggestions, refactors, and general improvements. For example, [49 of those are marked as enhancements](https://github.com/txt2tags/txt2tags/issues?q=is%3Aissue+is%3Aopen+label%3AType-Enhancement).
> 
> By the way, that list of open issues have some very old tickets (migrated from the old Google Code system) that may not even be relevant anymore. Surely we could do a clean up there.
Thank you for your clarification

**Comment by jendrikseipp** [comment]
From my point of view, at least the v3 branch is in "maintenance mode": we're happy to review pull requests, but aren't planning to make any big changes ourselves.

**Comment by dpy013** [comment]
> Hi @dingpengyu,
> 
> The latest development for txt2tags is happening in the [v3 branch](https://github.com/txt2tags/txt2tags/commits/v3) (maintained by @jendrikseipp) and is releasing new versions here: https://github.com/txt2tags/txt2tags/releases.
> 
> About those 120 opened issues, not all of them are problems, we also use the issue system for ideas, suggestions, refactors, and general improvements. For example, [49 of those are marked as enhancements](https://github.com/txt2tags/txt2tags/issues?q=is%3Aissue+is%3Aopen+label%3AType-Enhancement).
> 
> By the way, that list of open issues have some very old tickets (migrated from the old Google Code system) that may not even be relevant anymore. Surely we could do a clean up there.

Is it possible to set the v3 branch to the master branch?

**Comment by jendrikseipp** [comment]
Fine with me. What do you think @fgallaire ?

**Comment by fgallaire** [comment]
The v3 branch is not a real version of the software txt2tags, just a nice lib for an other software.
