### ISSUE TITLE
How to merge

### ISSUE THREAD

**Issue by echkourine25** [txt2tags/txt2tags#239]
Hello, i've writted some additionnal feature to txt2tags.py but like i'm a noob with git i want to ask you how to share my code with you to you to update it. Can you tell me where to search ? Is it with merge or something else ?

**Comment by waldyrious** [comment]
Hey @echkourine25 — I'm just a random GitHub user who's watching this repository, but I thought I'd let  you know that you can actually made edits directly in the web interface :) You can navigate to the [txt2tags.py](https://github.com/txt2tags/txt2tags/blob/v3/txt2tags.py) file, and then you'll see a pencil icon at the top right of the file.

If you click it (you may be prompted to create a fork of this repo), you will be sent to a web-based text editor, where you can paste the changes you've made directly, and at the bottom of the page  you'll have a "Propose changes" form which you can fill and click the green button to create a pull request. Let me know if this helps, or if anything is unclear :)

**Comment by echkourine25** [comment]
Hello @waldyrious 
All clear I will try what do you said thank you for the reply.
