### ISSUE TITLE
You should make a logo ...

### ISSUE THREAD

**Issue by blackcrack** [txt2tags/txt2tags#246]
Hi, 

i be at moment at mimetypes and search a logo for your lang.. but i had found nothing where i can take 
as logo for a text/x-txt2tags  = t2t  Mimetype "File" so can i only make a blank emty File with "t2t" file-type..
this is bad.. because.. it have easy no face for your Webpage, Files and others... it's a bit pity ...
have anyone a Bird at home, a Cat or an Waterdragon (who runs over water (Jesus walk over it ;) ) ;) )
or maybe an other Animal who fits ... well, it is give also other .. a special Icon who get the Character of you language.. so...
Gnu, Dolphin(SQL) and Feather is already assign :)
well.. come up with something, you are Developers you are have the feeling..  :smiley: 

best regards
Blacky

**Comment by flamenco108** [comment]
![image](https://user-images.githubusercontent.com/5072952/216755758-e82679f2-6eb3-4689-bc33-8f593d4fa448.png)

I thought that this is a logo of txt2tags.

**Comment by blackcrack** [comment]
@flamenco108 , thinking helps not many, what is if you wrong, then have i make a wrong icon x3  done for the next century.. in my icontheme at pling, under "blacky"
if for the whole exist time of this icontheme.. and other orient it at me.. think about .. ;)

It have to placed on the webside , wiki or somewhere to have something official...

what's about @Projectowner ?

@waldyrious, @jendrikseipp  could you speak about on your Forum/irc ?
best

**Comment by flamenco108** [comment]
I took this logo from the link to txt2tags.org on duckduckgo. AFAIR it was the logo. But now there is something else on the webpage: https://txt2tags.org/art.html
But look on the Facebook fanpage. The last edit from 2020 ant there is still the same logo.

**Comment by blackcrack** [comment]
because i ask also [Jendrik Seipp](https://github.com/jendrikseipp) ;)
he is one of the owners ..
@flamenco108  , Krzysztof,
i can also use the Octopus.. but looks a bit wired ..
maybe make they are a more new Version of an Iconic Logo
who can also use on a empty Letter(File) with recognition value...
we have 2023 and we can work with colors and high resolution...
if we look the Icon from Kate in Linux, the Modern blue Bird.. well.. 
and the Oktupus from Github, maybe other color and different coloured arms..
and a bit more modern .... but the way of github Octopus is not bad..
if i look on the red Octus mascot.. if it's more like the Github Mascot, 
but more modern maybe.. and modern like them blue Bird of Kate : 
https://phabricator.kde.org/T12594
https://phabricator.kde.org/file/data/l3amxj75apec7mt56h4v/PHID-FILE-tdqqjccxkfqzopn2ykm3/kate.png

but as Octopus in red....
:)

best

**Comment by fgallaire** [comment]
> ![image](https://user-images.githubusercontent.com/5072952/216755758-e82679f2-6eb3-4689-bc33-8f593d4fa448.png)
> 
> I thought that this is a logo of txt2tags.

It is.

**Comment by fgallaire** [comment]
> ![image](https://user-images.githubusercontent.com/5072952/216755758-e82679f2-6eb3-4689-bc33-8f593d4fa448.png)
> 
> I thought that this is a logo of txt2tags.

It is.

**Comment by blackcrack** [comment]
oky..

a entry in Wikipedia ? @fgallaire  ?

**Comment by blackcrack** [comment]
@fgallaire there a Screenshoot :)
a modern file, a W2K and a XP file (i be at moment on 3 different themes, take a look at pling.com and search "blacky"
![Screen 00000](https://user-images.githubusercontent.com/7925717/217227057-71c01287-3914-4c49-a7bb-5de08ed73c78.jpg)

but i must at first update the themefile :) make i in the next couples day's
best and have a good time :)

**Comment by fgallaire** [comment]
@blackcrack it's nice looking
